ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker' # We define the provider to use which is Docker, Start of instruction 1
Vagrant.configure("2") do |config| #Start of instruction 2
    config.vm.define "serveur_web" do |server_web| # We define a name for the instance we have to set up
    server_web.vm.network "forwarded_port", guest: 80, host: 9000 # We ask that port 9000 of the host be forwarded to port 80 of the container
    server_web.vm.provider "docker" do |server_web| # Start of instruction 3
    server_web.image = "datascientest:vagrant" # We define the docker image to use
    # admin.build_dir = "." # We can also define the location of the Dockerfile which is the current directory to build our image
    server_web.has_ssh = true # Possible connection in SSH
    server_web.privileged = true # Run the container with privileges on the underlying machine
    server_web.create_args = ["-v", "/sys/fs/cgroup:/sys/fs/cgroup:ro"] # We create a volume that connects our host's cgroup directory to our container's
            server_web.name = "server_web" #We define a name for our container
   end #End of statement 3
  end #End of instruction 2
end #End of instruction 1